### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by morki** [joffrey-bion/chrome-devtools-kotlin#197]
It would be super cool if this library can became multiplatform, as it can be used in Kotlin/Native projects to generate PDF from HTML.

**Comment by joffrey-bion** [comment]
Thanks for your comment. Until now nobody had a need for it, but I'll definitely look into it as it shouldn't be too hard.

Code-wise, almost nothing depends on JVM-specific things. Probably only docker-based tests will be a pain to run on macOS GitHub Actions runners.

**Comment by morki** [comment]
Thank you very much for your response and I am very happy :)

Maybe there will be some JVM only helpers, but as I looked at the code, it looks pretty multiplatform-ish :)

https://github.com/joffrey-bion/chrome-devtools-kotlin/blob/main/src/main/kotlin/org/hildan/chrome/devtools/domains/page/PageExtensions.kt

**Comment by joffrey-bion** [comment]
I'm currently attempting the multiplatform-ization of chrome-devtools-kotlin.

Here is a list of things that need to be taken care of:

* [x] `java.io.IOException` usage - solved by using Ktor's multiplatform alias
* [x] `java.nio.charset.Charset` usage - solved by using Ktor's multiplatform alias
* [x] `java.util.Base64` usage - solved by replacing with the experimental mpp base64 API from the Kotlin stdlib
* [x] `java.nio.Path` usage - solved by making `captureScreenshotToFile` a JVM-only helper
* [x] Publications of artifacts for Apple platforms require building on macOS agents - switched publication builds to macOS
* [x] GitHub Action's macOS runners don't support Docker out of the box, using a Colima setup
* [ ] (SKIPPED) `testcontainers` is not compatible with other platforms, and we'll need to switch to a Gradle-based setup. Keeping JVM-only tests for now.
* [ ] `testcontainers` don't seem to work out-of-the-box with Colima. Several experiments are needed. The env variables setup mentioned in [the Testcontainers docs](https://www.testcontainers.org/supported_docker_environment/#using-colima) don't seem to work on first try, but [Colima's own doc](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running) has some possible alternatives.
