### ISSUE TITLE
Release new version with Ktor 3

### ISSUE THREAD

**Issue by morki** [joffrey-bion/chrome-devtools-kotlin#457]
### Problem / use case

We are blocked on our project, because we cannot add this as dependency as in other projects, because we are using Ktor 3 here. It is not possible to migrate all our code to Ktor 2 to fix this. This library is failing in runtime with Ktor 3.

### Feature (solution)

Publish new version with Ktor 3. It is already merged and we tested locally with publishing to maven local, that it is fixing our problem.

**Comment by joffrey-bion** [comment]
Thank you for the nudge! I hear you. I had lots of problems with the macOS CI for a while so I was a bit tied in this.

I'll try to cut a release ASAP.

**Comment by joffrey-bion** [comment]
Finally managed to fix the CI, and could make a `6.5.0` release. Thanks for giving me the motivation to look into this again :)
