### ISSUE TITLE
Add utility to click on DOM element by selector

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/chrome-devtools-kotlin#91]

**Comment by cpdyj** [comment]
It's a huge work. In fact provide all event trigger api is a better work, but it's more difficult.

**Comment by joffrey-bion** [comment]
It's actually quite simple, I just tested the following and it works:

```kotlin
suspend fun ChromePageSession.clickOnElement(
    selector: CssSelector,
    clickDurationMillis: Long = 100,
    mouseButton: MouseButton = MouseButton.left
) {
    val box = dom.getBoxModel(selector) ?: error("Cannot click on element, no node found using selector '$selector'")
    val elementCenter = box.padding.center

    input.dispatchMouseEvent(
        DispatchMouseEventRequest(
            type = "mousePressed",
            x = elementCenter.x,
            y = elementCenter.y,
            button = mouseButton,
            clickCount = 1,
        )
    )
    delay(clickDurationMillis)
    input.dispatchMouseEvent(
        DispatchMouseEventRequest(
            type = "mouseReleased",
            x = elementCenter.x,
            y = elementCenter.y,
            button = mouseButton,
        )
    )
}
```

Actually simulating clicks like this is better than JS `.click()` because during in my tests the pop-ups open via JS were automatically blocked by chrome. Using simulated clicks acts "like a human" and is not blocked by chrome.

> In fact provide all event trigger api is a better work

What do you mean? You normally already have access to all events of all domains. Is there something in particular you didn't find?

**Comment by cpdyj** [comment]
I means if you provide a `clickOnElement` api, do we need a `keyDownOnElement` ? It will be a huge works... lol

**Comment by joffrey-bion** [comment]
I see your point. The idea is to ensure all low-level primitives are here (which should be the case, since all domains are generated), and then add some higher-level extensions on top of that for the most common use cases.

Clicking on an element is very common, maybe entering some data in an input field as well, this sort of things.
